### ISSUE TITLE
Build plugin required 'old' maven version

### ISSUE THREAD

**Issue by jmsnoeij** [OpenConext/OpenConext-csa#5]
Due to the use of the maven compass build plugin (for compiling CSS) the version of maven should be kept at 3.0.5 and cannot be upgraded. This results in problems when a new release is made, because this version of maven can only handle git version < 1.8.5

We need to update both tools without breaking the build on CSA.

**Comment by lvonk** [comment]
We don't use the maven compass plugin anymore.
