### ISSUE TITLE
build tooling needs to be updated

### ISSUE THREAD

**Issue by jmsnoeij** [OpenConext/OpenConext-csa#6]
In CSA a ruby gem maven plugin is used for compiling sass code, this ruby gem is dependent on maven 3.0.X (http://stackoverflow.com/questions/18956959/java-lang-noclassdeffounderror-org-sonatype-aether-repositorysystemsession).

This version of maven cannot handle the new layout of the git command introduced in git 1.8.5 (http://mail-archives.apache.org/mod_mbox/maven-users/201312.mbox/%3CCALYGm1z8L2qm9tfQc0qzscWSJEx=L9CvvtceJq6Ayfe-kF+vdQ@mail.gmail.com%3E).

These two combined completely lock our build tools to specific versions, we need to resolve this and upgrade the build tooling.

**Comment by lvonk** [comment]
We don't us the ruby maven gem anymore.
